pretrained_base_model_path: "ckpts/sd-image-variations-diffusers"
pretrained_vae_path: "ckpts/sd-vae-ft-mse"
image_encoder_path: "ckpts/sd-image-variations-diffusers/image_encoder"

denoising_unet_path: "ckpts/ViViD/denoising_unet.pth"
reference_unet_path: "ckpts/ViViD/reference_unet.pth"
pose_guider_path: "ckpts/ViViD/pose_guider.pth"

motion_module_path: "ckpts/MotionModule/mm_sd_v15_v2.ckpt"

inference_config: "./configs/inference/inference.yaml"
weight_dtype: 'fp16'


model_video_paths:
  - "data/videos/lower1.mp4"

cloth_image_paths:
  - "data/cloth/051985_1.jpg"
  - "data/cloth/051990_1.jpg"